#!/bin/bash
# modified from https://github.com/Anachron/i3blocks/blob/master/blocks/battery

BATTERY_STATE=$(cat /sys/class/power_supply/BAT0/status)
BATTERY_POWER=$(cat /sys/class/power_supply/BAT0/capacity)

URGENT_VALUE=10

if [[ "${BATTERY_STATE}" = "Charging" ]]; then
  echo "CHR ${BATTERY_POWER}%"
  echo "CHR ${BATTERY_POWER}%"
  echo ""
elif [[ "${BATTERY_STATE}" = "Discharging" ]]; then
  echo "BAT ${BATTERY_POWER}%"
  echo "BAT ${BATTERY_POWER}%"
  echo ""
else
  echo "${BATTERY_POWER}%"
  echo "${BATTERY_POWER}%"
  echo ""
fi

if [[ "${BATTERY_POWER}" -le "${URGENT_VALUE}" ]]; then
  exit 33
fi
