#!/bin/bash

build_from_aur(){
  local tarball=$1
  local file=$(basename $tarball)
  local base=${file%%.*}

  echo $base
  set +o verbose
  mkdir -p ~/AUR/$base
  mv $tarball ~/AUR/$base
  cd ~/AUR/$base
  tar -xvf $file
  cd ~/AUR/$base/$base
  pwd
  echo installing $base
  makepkg -sri
}

