#!/bin/bash

build_from_aur(){
  local tarball=$1
  local file=$(basename $tarball)
  local base=$($file%%.*)

  set +o verbose
  mkdir -p ~/AUR/$base
  mv $tarball ~/AUR/$base/
  cd ~/AUR/$base
  tar -xvf $file
  makepkg -sri
}

